version: "3.8"
services:
  app:
    build: .
    environment: # check out pepic/config/app.go for more env variables
      - BASE_URL=http://i.phangan.me/
      - STORAGE_DIR=/uploads
      - SECRET_CODE=w@tareyoulooking?
      - IMAGE_ORIGINAL_LENGTH=1400
      - MAX_UPLOAD_SIZE=100M
    volumes:
      - ./uploads:/uploads
    ports:
      - 8118:8118
    user: "1000" # set your real uid (by default only root can read the uploaded files)
    restart: unless-stopped
